Repository S0LD13R-CMD/Messaging-App, pull requests merged in 2025-04, with the labels that each got.

#50 Update CI/CD workflow to include 'master' branch and bump @types/reac…
  .github/workflows/ci.yml
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/chat/PrivateChat.tsx
Labels: DevOps Eng

#54 Websockets V1
  messaging.app/chat-frontend/src/api/auth.ts
  messaging.app/chat-frontend/src/components/GlobalChat.tsx
  messaging.app/chat-frontend/src/components/Login.tsx
  messaging.app/chat-frontend/src/components/Navbar.tsx
  messaging.app/chat-frontend/src/components/PrivateChat.tsx
  messaging.app/chat-frontend/src/components/Register.tsx
  messaging.app/chat-frontend/src/components/UserList.tsx
  messaging.app/chat-frontend/src/components/WebSocketEchoTester.tsx
  messaging.app/chat-frontend/src/context/AuthContext.tsx
  messaging.app/pom.xml
  messaging.app/src/main/java/com/qmul/messaging/app/config/SecurityConfig.java
  messaging.app/src/main/java/com/qmul/messaging/app/config/WebSocketConfig.java
  messaging.app/src/main/java/com/qmul/messaging/app/config/WebSocketHandshakeInterceptor.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/AuthenticationController.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/MessageController.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/WebSocketEchoTestController.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/WebSocketGlobalChatController.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/WebSocketPrivateChatController.java
  messaging.app/src/main/java/com/qmul/messaging/app/repository/PrivateMessageRepository.java
Labels: Backend Dev

#67 Refactor CI workflow to streamline deployment process by replacing SS…
  .github/workflows/ci.yml
Labels: DevOps Eng

#135 Dynamic Message Loading
  messaging.app-frontend/src/api/auth.ts
  messaging.app-frontend/src/api/globalMessages.ts
  messaging.app-frontend/src/components/GlobalChat.tsx
  messaging.app/src/main/java/com/qmul/messaging/app/config/SecurityConfig.java
  messaging.app/src/main/java/com/qmul/messaging/app/config/WebConfig.java
  messaging.app/src/main/java/com/qmul/messaging/app/controller/MessageController.java
  messaging.app/src/main/java/com/qmul/messaging/app/repository/GlobalMessageRepository.java
  messaging.app/src/main/resources/application.properties
Labels: bug
